Create scurve
pratima-shegokar/perflow pull request #65
Opened 2019-12-09 13:27 UTC by abdnaqip1980

not connected to the backend yet

2019-12-10 11:52 UTC, jshortz requested changes
Why is so much of App.js rewritten (agree with changing all single quotes to double for consistency, but it looks like a lot of the Routers were also overwritten without changes - this can cause issues)?

s-curve should be in the logged in Navbar (is currently in the logged out navbar), I think?

Suggest adding margins to the div holding the chart so that the graph doesn't fill the whole screen.

2019-12-10 12:22 UTC, MelanyCristy reviewed
Check the comments i made in your pull request, reply them and/or make the changes suggest it.

2019-12-10 12:22 UTC, MelanyCristy commented on frontend/src/App.js
> +import Navbar from "./components/Navbar";
The recommendable is use a single quote. So, it was fine before but it's okay

2019-12-10 12:22 UTC, MelanyCristy commented on frontend/src/App.js
If you were reformatting, you missed a few blank spaces

2019-12-10 12:22 UTC, MelanyCristy commented on frontend/src/App.js
blank space

2019-12-10 12:22 UTC, MelanyCristy commented on package-lock.json
> -  "requires": true,
Why is all this deleted from the package-lock.json?

2019-12-10 12:26 UTC, MelanyCristy commented on frontend/src/App.js
> +import Navbar from "./components/Navbar";
Also you only changed it in one component (App.js) so this creates inconsistency in our code. I suggest to put it back as it was before or someone eventually will do it in a different task.

2019-12-10 12:39 UTC, MelanyCristy commented on frontend/src/components/Navbar.js
> +                                <a class="nav-link" href="/scurve">Scurve</a>
Why have the link in the navbar? Isn’t supposed to be inside the Project Page?

2019-12-11 08:32 UTC, abdnaqip1980 commented
It is overridden by link-projectpanel-to-scurve pull request

2019-12-11 08:32 UTC, closed without merging